### ISSUE TITLE
Slack generates "@jessfraz" when "kata" typed in IRC

### ISSUE THREAD

**Issue by annabellebertooch** [kata-containers/community#32] opened 2018-06-06 15:12 UTC
In both #kata-dev and #kata-general channels on IRC, when a user types "kata", Slack generates "@/jessfraz".  When jessfraz sends a message in Slack, the IRC user shows up as "kata".

Two weeks ago I made the user "@/kat" on Slack to see if it would jump to pinging that instead, but no dice--stills pings jessfraz.

cc @jbryce

**Comment by jessfraz** [comment] 2018-06-06 15:13
lmao this is my favorite issue on this website

**Comment by jessfraz** [comment] 2018-06-06 15:13
closing as "working as intended"... just kidding

**Comment by kat** [comment] 2018-06-07 02:37
I am the user @kat - so please don't send stuff to me. Thanks!

—
Kat Szuminska

--- original message ---
On Thu, Jun 7, 2018 at 01:12 am, <notifications@github.com> annabellebertooch wrote:


In both #kata-dev and #kata-general channels on IRC, when a user types "kata", Slack generates "@jessfraz".

Two weeks ago I made the user "@kat" on Slack to see if it would jump to pinging that instead, but no dice--stills pings jessfraz.

cc @jbryce

—

You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by grahamwhaley** [comment] 2019-02-13 15:43
Heh heh, I think we all know of this, and it has been discussed why it happens etc. (it is an ordering lookup thing, and jfrazz just happens to be the first person in the list which is the default if the lookup fails iirc...).

I'm going to close this, as afaik there was no easy practical fix. And, tbh, I've not seen it happen too often recently.

**Closed by grahamwhaley** 2019-02-13 15:43 UTC
